---
- name: Ensure /opt/bctools/mysqlbackup directory has correct permissions.
  file:
    path: /opt/bctools/mysqlbackup
    state: directory
    owner: root
    group: root

- name: Clone repository
  git:
    repo: https://github.com/nunogrl/mysqlbackup.git
    version: master
    dest: /opt/bctools/mysqlbackup
    accept_hostkey: yes
  become: yes

- name: Add cronjob
  template:
    src: bcbackup.j2
    dest: /etc/cron.d/bcbackup
