----
- name: Ensure MySQL is installed
  apt:
    name: mysql-server
    state: present

- name: Create a new database with name 'barbeartestes0123'
  mysql_db:
    name: barbeartestes0123
    state: present
    register: bc_present

- name: display output
  debug: msg= "{{ bc_present.stdout_lines | to_nice_json }}"


- name: MySQL | adduser simplemachines
    name: simplemachines
    password: 12345
    priv: '*.*:ALL,GRANT'
    state: present




- name: Verify that db exists
  script: files/check_bcDB.sh
  register: bcdbpresent
  tags: installDB

- name: Check disk space
  assert:
    that:
      mount.size_available > mount.size_total | float * 0.1
  vars:
    mount: "{{ ansible_mounts | selectattr('mount','equalto','/')|list|first }}"
  register: disk_free
  no_log: True
  ignore_errors: True
  tags: patching

- fail: msg="not enough disk space to perform update"
  when: disk_free|failed
  tags: installDB



- name: Create a new database with name 'barbearclassico'
  when: bcdbpresent|true
  mysql_db:
    name: barbearclassico
    state: present

- name: Copy database dump file
  copy:
    src: dump.sql.bz2
    dest: /tmp
- name: Restore database
  mysql_db:
    name: my_db
    state: import
    target: /tmp/dump.sql.bz2

- name: Dump all databases to hostname.sql
  mysql_db:
    state: dump
    name: all
    target: /tmp/{{ inventory_hostname }}.sql

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    state: import
    name: all
    target: /tmp/{{ inventory_hostname }}.sql
